-- USERS TABLE
CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    streak INTEGER DEFAULT 0,
    last_active DATE,
    created_at TIMESTAMP DEFAULT NOW()
);


